owner: excalidraw
repo: upptime

sites:
  - name: Excalidraw
    url: https://excalidraw.com
    icon: https://excalidraw.com/favicon.ico
  - name: Excalidraw Collaboration
    url: https://portal.excalidraw.com
  - name: Excalidraw Storage
    url: https://json.excalidraw.com
  - name: Excalidraw Libraries
    url: https://libraries.excalidraw.com
  - name: Excalidraw Blog
    url: https://blog.excalidraw.com

status-website:
  cname: status.excalidraw.com
  name: Excalidraw Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/excalidraw/excalidraw
    - title: Excalidraw
      href: https://excalidraw.com
    - name: Blog
      url: https://blog.excalidraw.com

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
