owner: excalidraw
repo: upptime

sites:
  - name: Excalidraw
    url: https://excalidraw.com
  - name: Excalidraw Storage
    url: https://json.excalidraw.com
  - name: Excalidraw Libraries
    url: https://libraries.excalidraw.com
  - name: Excalidraw Blog
    url: https://blog.excalidraw.com

status-website:
  baseUrl: /upptime
  name: Excalidraw Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/excalidraw/excalidraw
    - title: Excalidraw
      href: https://excalidraw.com
