owner: excalidraw
repo: upptime

sites:
  - name: Excalidraw
    url: https://excalidraw.com
  - name: Excalidraw Storage
    url: https://json.excalidraw.com
  - name: Excalidraw Libraries
    url: https://libraries.excalidraw.com
  - name: Excalidraw Blog
    url: https://blog.excalidraw.com
